### PR TITLE
[add] Bring node-config into fluct

### PR DESCRIPTION
**Pull request by srphcr**
I added node-config & make it be able to use code-config for lambda.
This changes will include config directory into the zip.

### CODE REVIEW

**Comment by r7kamura** [comment]
Thanks for your PR :yum: 
I haven't used node-config (or code-config?) before. Can you explain in what situations it helps us?

**Comment by srphcr** [comment]
Sometimes we need to prepare some of stages & deploy to other environments.
These stages or env needs each application configurations.
So, I think it's useful to switch the configurations.
With this module, we can switch the configurations by the filename.
https://github.com/lorenwest/node-config/wiki/Configuration-Files

For example, facebook application key & secret or something.

**Comment by srphcr** [comment]
So in fact, I also want to move region, stage, accountid, restapiid & rolename into config/{environment}.json or something.

**Comment by r7kamura** [comment]
I see :+1: 

I think you may already know that it also can be done by putting symlink like `./actions/*/config -> ./config`  and manually installing `node-config` in your application. What is the strong reason to officially support node-config in fluct? for user-friendliness?

**Comment by r7kamura** [comment]
> So in fact, I also want to move region, stage, accountid, restapiid & rolename into config/{environment}.json or something.

Okay, that makes sence. I also have the same issue about handling multiple accounts :crossed_flags:

**Comment by srphcr** [comment]
Thank you for merging!

**Comment by r7kamura** [comment]
I just published `fluct@0.3.2` :tada:

**Comment by r7kamura** [comment]
It would be very helpful if you add some explanation about node-config usage in [FAQ](https://github.com/r7kamura/fluct/blob/master/docs/faq.md) page :innocent:

**Comment by srphcr** [comment]
Thank you so much!

Do we have any rules to write the faq.md?
And, is it ok to just paste reference urls?

**Comment by r7kamura** [comment]
All right, there is no rule. Don't be so serious :smile:

**Comment by srphcr** [comment]
Okay.
I will paste some references on faq.md.

**Pull request merged**
